@host= https://localhost:7284
GET {{host}}/Dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYjkyNzg1ZS0zYTZiLTRlOTYtYWYwMi1mOGZkM2U3MGM0YmIiLCJnaXZlbl9uYW1lIjoiQmFiYWNhciIsImZhbWlseV9uYW1lIjoiU2VjayIsImp0aSI6IjYyNzhhMTZlLWY4MWQtNDNmOC04ZTQ0LWYwZTM0MTcxN2FjYyIsImV4cCI6MTY2ODM4Mjk3MSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.1Bw98YwnR5fCHN_6FwMgCpp8IENyt5VSle8o636Cy7M
