@host= https://localhost:7284
POST  {{host}}/auth/register
Content-Type: application/json

{
    "firstName" : "",
    "lastName" : "",
    "email" : "babacarseckdevweb@gmail.com",
    "password" : "test2022"
}
